services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://myvs.download.prss.microsoft.com/dbazure/en_windows_10_business_editions_version_1903_updated_july_2020_x64_dvd_7c95f7e0.iso?t=975400b1-56fa-4647-90c6-5cfe8b33c121&P1=1775261001&P2=601&P3=2&P4=ttGh5ybk8acpSO2sPvEqaEAViv9FibCEAiuZlmPh3uCL3IVY%2B4fYc%2B7BrbcZhzEKk1%2F66AfomcyFKiKJRZg4xb%2BZ1AG7NzLYBp8ZfrZ%2Fpb2vQSZuj18D98qrSuhwTYwbgWLCSgTVzwVzLZZhyZ1a4erqMfaOejMZp6OwanPlwFMS4yPCaySwsjErERuV8cMAslo90FwNRJ0NHlOc6vZSXs6ZlU%2FXIfBw%2Ba%2Bea8CwECUvDHQZCvkblqnKwqmWUKY%2BnhTnZ8TYuCq%2BCXDbFzbXWwg86ZrL11WRfPTNHX%2F6%2FLqP5pMA1VMsE7vnaOxEaoC31XIlM77LZBmOyBf56HFS3A%3D%3D&su=1"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
